defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-26-alpha
  environment:
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cgps/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew assembleRelease check
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "cgps/build.gradle" }}
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/build/test-results/testDebug*/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_artifacts:
          path: cgps/build/reports
          destination: reports
      - store_test_results:
          path: ~/junit
      - persist_to_workspace:
          root: ./
          paths:
            - ./
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          context: org-global
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/